%%%%%% THIS FILE CONTAINS THE STANDARD PARSER WE WILL TEST
%%%%%% YOUR LEXICON WITH
%%%%%%
%%%%%% DO NOT EDIT THIS FILE

%%%%%% FOR Q5, EDIT q5_parser.pl

/* Noun phrase can be a proper name or can start with an article */

np([Name], Name) :- proper_noun(Name).
np([Art | Rest], What) :- article(Art), np2(Rest, What).


/* If a noun phrase starts with an article, then it must be followed
   by another noun phrase that starts either with an adjective
   or with a common noun. */

np2([Adj | Rest], What) :- adjective(Adj, What), np2(Rest, What).
np2([Noun | Rest], What) :- common_noun(Noun, What), mods(Rest, What).

/* Modifier(s) provide an additional specific info about nouns.
   Modifier can be a prepositional phrase followed by none, one or more
   additional modifiers.  */

mods([], _).
mods(Words, What) :-
	append(Start, End, Words),
	prepPhrase(Start, What), mods(End, What).

prepPhrase([Prep | Rest], What) :-
	preposition(Prep, What, Ref), np(Rest, Ref).